### ISSUE TITLE
Comp Alloc

### ISSUE THREAD

**Issue by AVHuntley** [AVHuntley/TM-Supply-A3-Migration#3]

**Comment by A3Huntley** [comment]
Disabled 'grand' formatting

Added Insert script. <strike>Still debugging a JSON error related to Insert</strike>

**Comment by A3Huntley** [comment]
enabled DoNotSend columns. Maked columns 3 and 4 (out of 4) as DoNotSend (ReadOnly). This prevents an error on submit re duplicate cells

**Comment by AnnaKraw** [comment]
Unable to submit data. Error message attached.


![Image](https://github.com/user-attachments/assets/3e74ce90-0daa-4697-b751-0c9740189d85)

**Comment by AnnaKraw** [comment]
Please change sheet to unprotected.

**Comment by A3Huntley** [comment]
Unlocked all cells on the sheet. I think before only the blue cells were unlocked for input, as the rest contained formulas. But you should now be able to overwrite formulas.
